### ISSUE TITLE
MVP and Schema issues

### ISSUE THREAD

**Issue by OhBall** [miketu926/GetStarted#1]
- [x] Payment info should never be stored in plaintext in our database. Proper CC payments are only a bonus MVP, so for now I wouldn't include the `payment_info` table. If you make it to that MVP, you can refactor, but for something like real payments, you'll have to use an outside API to actually process the transactions anyway.

- [x] As a part of your MVP's, you note that a user should be able to upload images for their projects. However, I don't see anything in your schema to reflect this.

- [x] It's not a requirement, but listing associations would be a good idea.

**Comment by miketu926** [comment]
1. Updated to include the CC payments as a bonus feature
2. Updated both users & projects table to reflect picture url in each (I am considering project image/video to be uploaded)
